### ISSUE TITLE
Does not work with tz-aware DatetimeIndex.

### ISSUE THREAD

**Issue by kyrre** [martijnvermaat/calmap#12]
If the DatetimeIndex contains tzinfo the entries in the calmap are blank.

![example](https://cloud.githubusercontent.com/assets/433518/16707695/1b78b2ea-45d8-11e6-8bd2-2a38a395bf4e.png)

**Comment by martijnvermaat** [comment]
Thanks for reporting this @kyrre !

I'm not sure when I'll have time to look at this though. PR welcome ;)

**Comment by karlicoss** [comment]
It actually may be considered a feature?, E.g. it's unambiguous if timezone is same, but what do you do if your timestamps come in different timezones? Ultimately it's up to the user to figure out what they want and strip off the timezone.
Would be nice to add a more explicit error message though.

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
