### ISSUE TITLE
FutureWarning: how in .resample() is deprecated 

### ISSUE THREAD

**Issue by kidpixo** [martijnvermaat/calmap#13]
Using how in return a Future Warning 

```
/Users/xxxx/.virtualenvs/calmap/lib/python2.7/site-packages/calmap/__init__.py:294: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).count()
  by_day = data.resample('D', how=how)
```

should be easy to fix, I'll see if i can submit a PR.

**Comment by kidpixo** [comment]
Uhm it's harder than I thought , see here for the new Pandas resample API : [What’s New — pandas 0.18.0 documentation](http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#resample-api)

**Comment by martijnvermaat** [comment]
Thanks, this is being tracked in #10 so I'm closing this. PR would be very welcome.
