### ISSUE TITLE
Border between two continuous months & day numbers in cells

### ISSUE THREAD

**Issue by nhanitvn** [martijnvermaat/calmap#14]
Thanks for a useful calendar heatmap package. Is it easy to add the two above features?
For the 1st one, an example is black lines in [https://bl.ocks.org/mbostock/4063318]

**Comment by martijnvermaat** [comment]
Yes, I would love to have these features :+1:

I think day numbers (or heatmap values) in cells would have to be drawn manually. So it would take some fiddling for correct positioning, but should be possible.

Lines separating months will be quite hard unfortunately, or at least I don't see an easy way to do it.

**Comment by rightx2** [comment]
@martijnvermaat I think there is a good solution for this: https://github.com/rougier/calendar-heatmap/blob/master/calendar-heatmap.py. Hope this one to be merged in the calmap

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
