### ISSUE TITLE
Deprecation warnings with Matplotlib 2.0.x

### ISSUE THREAD

**Issue by janik6n** [martijnvermaat/calmap#19]
When run with Matplotlib 2.0.2 (Python 3.6.2) I get the following deprecation warnings:

```
/.../venv/lib/python3.6/site-packages/calmap/__init__.py:128: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).sum()
  by_day = data.resample('D', how=how)
/.../venv/lib/python3.6/site-packages/calmap/__init__.py:146: MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.
  linecolor = ax.get_axis_bgcolor()
```
Just a heads up for future proofing.

**Comment by MarvinT** [comment]
as of matplotlib 2.2.2 get_axis_bgcolor() has been removed and calmap no longer works

**Comment by BreitA** [comment]
replace 
linecolor = ax.get_axis_bgcolor()

with 

linecolor = ax.get_fc()

**Comment by darkmatter2222** [comment]
Opened pull request https://github.com/martijnvermaat/calmap/pull/34 to fix, emailed @martijnvermaat to pull.

**Comment by MarvinT** [comment]
@darkmatter2222 , can you submit a PR to https://github.com/MarvinT/calmap/ as well. Thats the version that currently gets published to pypi. Unless @martijnvermaat wants to take over the repo maintenance again.

**Comment by darkmatter2222** [comment]
Hey, that's up to @martijnvermaat. I'm personally a big fan of this package! love to make future enhancements. Got all sorts of ideas.

**Comment by darkmatter2222** [comment]
@MarvinT got some conflicts there m8 https://github.com/MarvinT/calmap/pull/11

**Comment by martijnvermaat** [comment]
Right! I knew someone had offered help before, but I completely forgot about this!

@MarvinT Since it sounds you're still interested in keeping your version maintained, let's promote that to the be the main repo. I can add a notice on this repo and in the README pointing to yours, and also mention in all open issues and pull request.

@darkmatter2222 It would be great if you could submit the same PR to @MarvinT 's fork, thanks!

**Comment by darkmatter2222** [comment]
@martijnvermaat,  https://github.com/MarvinT/calmap/pull/11 submitted, in @MarvinT bucket now.

**Comment by darkmatter2222** [comment]
closed https://github.com/MarvinT/calmap/pull/11, the source is nothing alike. @MarvinT had this solved for in another way. 

I would say this repo is also out of date too.  thanxz all!

**Comment by MarvinT** [comment]
@darkmatter2222 yup, I think solving this issue is what prompted me to take over maintenance of the repo in the first place. Definitely let me know if there are any new features fixes you'd like to add over there

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
