### ISSUE TITLE
Color of year labels separate

### ISSUE THREAD

**Issue by Thomasillo** [martijnvermaat/calmap#20]
If fillcolor is specified, it's also used as the color for the yearlabels. This can be very impractical if you want days with no data to be shown in white. Then the yearlabels vanish.

**Comment by tomkwok** [comment]
This is fixed with the addition of a `yearcolor` argument with a default non-white non-light-color value for `calplot` in [calplot](https://github.com/tomkwok/calplot).

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
