### ISSUE TITLE
Possibility to limit months

### ISSUE THREAD

**Issue by robroc** [martijnvermaat/calmap#21]
Great tool, thank you for making this.

I'm visualising extreme cold temperatures, and these only happen from December through March. It would be nice to be able to limit months in the plot and rearrange them to overlap years.

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
