### ISSUE TITLE
Bug with the 'sum' aggregation.

### ISSUE THREAD

**Issue by yygrechka** [martijnvermaat/calmap#27]
When I run the code on the doc page:
import numpy as np; np.random.seed(sum(map(ord, 'calmap')))
import pandas as pd
import calmap

all_days = pd.date_range('1/15/2014', periods=700, freq='D')
days = np.random.choice(all_days, 500)
events = pd.Series(np.random.randn(len(days)), index=days)
calmap.yearplot(events, year=2015)
I get the following result:
![screenshot1](https://user-images.githubusercontent.com/19693279/52193493-3d018200-2804-11e9-9a1c-e6beb7de5fb2.png)
Only when I change the aggregation to be mean, I get the expected result:

calmap.yearplot(events, year=2015,how=u'mean')
![screenshot from 2019-02-03 22-36-33](https://user-images.githubusercontent.com/19693279/52193506-4ee32500-2804-11e9-9630-ae62f449d917.png)

python version: 3.7.1 
pandas version: 0.23.4
calmap version: 0.0.7
matplotlib version: 3.0.1

**Comment by tomkwok** [comment]
This is fixed with the addition of a `dropzero` argument with a default True value for `calplot` in [calplot](https://github.com/tomkwok/calplot).

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
