### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by sibbl** [martijnvermaat/calmap#31]
In version 1.0.0 of Pandas, `Series.ix` and `DataFrame.ix` was removed, breaking calmap. See https://pandas.pydata.org/docs/whatsnew/v1.0.0.html 

However, this method is still used at https://github.com/martijnvermaat/calmap/blob/83e2a9a0bdc773c9e48e05772fb412ac8deb8bae/calmap/__init__.py#L220

**Comment by markryanandrews** [comment]
the line should be:
`ax.set_xticks([by_day.loc[datetime.date(year, i + 1, 15)].week `

ix is no longer used in pandas, loc will fix your problem

**Comment by aliutkus** [comment]
hi, ok, so I understand we cannot use calmap anymore ? is there a fix ?

**Comment by ddm-j** [comment]
@aliutkus until the author fixes this problem, you can open up the `__init__.py` file (for me this is located in C:\Users\"username"\anaconda3\site-packages\calmap" and CTRL+F search for `ax.set_xticks` and replace the line with what @markryanandrews has suggested. I've just updated the line and it is working fine now.

**Comment by XiaosongWen** [comment]
> @aliutkus until the author fixes this problem, you can open up the `__init__.py` file (for me this is located in C:\Users"username"\anaconda3\site-packages\calmap" and CTRL+F search for `ax.set_xticks` and replace the line with what @markryanandrews has suggested. I've just updated the line and it is working fine now.

for those who are not using anaconda, the address is like "C:\Users\username\AppData\Local\Programs\Python\Python38-32\Lib\site-packages"

**Comment by asaljalilvand** [comment]
Hi, I also faced this issue, and I found another library,[calplot](https://pypi.org/project/calplot/), which says it's a fork of calmap with some fixes. It works for me.

**Comment by darkmatter2222** [comment]
Opened pull request https://github.com/martijnvermaat/calmap/pull/34 to fix, emailed @martijnvermaat to pull.

**Comment by darkmatter2222** [comment]
Resolved with the https://github.com/martijnvermaat/calmap/pull/34 merge, @martijnvermaat  can mark this issue resolved/closed.

**Comment by MarvinT** [comment]
Hi, if this problem still exists and you'd like to create a PR to fix it please direct it to https://github.com/MarvinT/calmap/
That is the version that gets published to pypi and has received several updates to fix some existing issues.

**Comment by martijnvermaat** [comment]
Thank you for creating the issue. Unfortunately I don't have the time to maintain this project. As per @MarvinT 's comment, please see https://github.com/MarvinT/calmap/ instead.
