### ISSUE TITLE
 'fillcolor' in calmap.calendarplot doesn't work right

### ISSUE THREAD

**Issue by Starrry22** [martijnvermaat/calmap#32]
when i use calmap.calendarplot without 'fillcolor', this is the result
![image](https://user-images.githubusercontent.com/37425883/124444109-da37ba80-ddb0-11eb-84a0-31fcde1c3dea.png)
and when i use calmap.calendarplot with 'fillcolor', this is the result, it adds the label of year
![image](https://user-images.githubusercontent.com/37425883/124444246-fb98a680-ddb0-11eb-9b00-b1215635ead7.png)

**Comment by darkmatter2222** [comment]
@Starrry22, post your code snips?

**Comment by Starrry22** [comment]
> @Starrry22, post your code snips?

Thanks, i found the "calplot" library, and it solved my problem
